#pragma config(Sensor, dgtl1,  Claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  DownArm,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  UpArm,          sensorDigitalOut)
#pragma config(Motor,  port4,            a,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Loop Forever
	int clawset=0;
	while(1 == 1)
	{
		/*if (vexRT[Btn5UXmtr2] == 1){
			SensorValue(Sol_B) = 0;
			SensorValue(Sol_A) = 1;

			}else{
			SensorValue(Sol_B) = 1;
			SensorValue(Sol_A) = 0;*/



			//Remote Control Commands (dual joystick drive for wheel)
			if (abs(vexRT[Ch2]) > 15 || abs(vexRT[Ch3]) > 15 || vexRT[Btn7L] == 1 || vexRT[Btn8R] == 1){
				motor[backRight] = vexRT[Ch2] * 0.8 + vexRT[Btn7L] * 60 - vexRT[Btn8R] * 60;
				motor[backLeft] = vexRT[Ch3] * 0.8 - vexRT[Btn7L] * 60 + vexRT[Btn8R] * 60;
				//motor[Conv] = vexRT[Btn6U] * 70 + vexRT[Btn6D] * (-70);
				//
				//motor[FW2] = vexRT[Btn6UXmtr2] * 256;
			}else{
				motor[backRight] = 0;
				motor[backLeft] = 0;
				//motor[Conv] = 0;
				//motor[FW1] = 0;
				//motor[FW2] = 0;
			}
			//motor[Intake] = vexRT[Btn7UXmtr2] * 256 - vexRT[Btn7DXmtr2] * 256;
			//motor[Arm]=vexRT[Ch3Xmtr2] * 0.8;

			if(vexRT[Btn6DXmtr2]==1&&clawset==0){
				SensorValue(Claw) = 1;
				clawset=1;
			}
			if(vexRT[Btn6UXmtr2]==1&&clawset==1){
				SensorValue(Claw) = 0;
				clawset=0;
			}
			SensorValue(UpArm)=vexRT[Btn5UXmtr2];
			SensorValue(DownArm)=vexRT[Btn5DXmtr2];

		}

	}
